# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autoheal < Formula
  desc "Autoheal platform CLI — investigations, chat, and the whole API"
  homepage "https://autoheal.ai"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/accelos/autoheal-cli/releases/download/v0.1.0/autoheal_0.1.0_darwin_amd64.tar.gz"
      sha256 "b6c3f1747e1e2ca98b08a9c9143b1d4e993233d4eabb2c832a6b8b51d1c6ebd2"

      define_method(:install) do
        bin.install "autoheal"
        bin.install_symlink "autoheal" => "ah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/accelos/autoheal-cli/releases/download/v0.1.0/autoheal_0.1.0_darwin_arm64.tar.gz"
      sha256 "1f77be04e7cd641cee54e28a36287335e72d0de5625f9b8cc0cef864da35c7f1"

      define_method(:install) do
        bin.install "autoheal"
        bin.install_symlink "autoheal" => "ah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/accelos/autoheal-cli/releases/download/v0.1.0/autoheal_0.1.0_linux_amd64.tar.gz"
      sha256 "c152ec44783ec74213cc7fbf8a43355dbc850e82ec9df83d4f52586690a4a272"
      define_method(:install) do
        bin.install "autoheal"
        bin.install_symlink "autoheal" => "ah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/accelos/autoheal-cli/releases/download/v0.1.0/autoheal_0.1.0_linux_arm64.tar.gz"
      sha256 "c237a561b72a075ae7b1672d4d470a53ef6729a955e1b9b076fa6a27ce925337"
      define_method(:install) do
        bin.install "autoheal"
        bin.install_symlink "autoheal" => "ah"
      end
    end
  end

  test do
    system "#{bin}/autoheal", "version"
  end
end
